# Generated by Django 6.1.1 on 2026-09-26 18:14

import django.db.models.deletion
import django.utils.timezone
import django_trmnl_byos.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('layout', models.CharField(choices=[('1x1', 'Full screen'), ('1Lx1R', '1 left, 1 right'), ('1Tx1B', '1 top, 1 bottom'), ('1Lx2R', '1 left, 2 right'), ('2Lx1R', '2 left, 1 right'), ('2Tx1B', '2 top, 1 bottom'), ('1Tx2B', '1 top, 2 bottom'), ('2x2', '2 x 2 grid'), ('3x3', 'Fluid (3 x 3 grid)')], default='1x1', max_length=10)),
                ('backdrop', models.BooleanField(default=False, help_text='Patterned background behind mashup views.')),
                ('dark_mode', models.BooleanField(default=False)),
                ('no_bleed', models.BooleanField(default=False, help_text="Remove the screen's outer padding.")),
                ('extra_screen_classes', models.CharField(blank=True, help_text='More classes for the screen element, e.g. screen--scale-xxsmall.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='TRMNL', max_length=100)),
                ('mac_address', models.CharField(max_length=17, unique=True)),
                ('api_key', models.CharField(default=django_trmnl_byos.models.generate_api_key, max_length=64, unique=True)),
                ('friendly_id', models.CharField(default=django_trmnl_byos.models.generate_friendly_id, max_length=6, unique=True)),
                ('profile', models.CharField(choices=[('og', 'TRMNL OG (1-bit)'), ('og_2bit', 'TRMNL OG (2-bit, firmware 1.6+)'), ('x', 'TRMNL X (4-bit)')], default='og', max_length=20)),
                ('orientation', models.CharField(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait')], default='landscape', max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('refresh_rate', models.PositiveIntegerField(default=900, help_text='Seconds between wake-ups.')),
                ('playlist_position', models.PositiveIntegerField(default=0, editable=False)),
                ('battery_voltage', models.FloatField(blank=True, editable=False, null=True)),
                ('rssi', models.IntegerField(blank=True, editable=False, null=True)),
                ('firmware_version', models.CharField(blank=True, editable=False, max_length=20)),
                ('reported_model', models.CharField(blank=True, editable=False, max_length=50)),
                ('reported_refresh_rate', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False, help_text='New devices start on this playlist.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PluginInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plugin', models.CharField(help_text='Which plugin draws this instance.', max_length=50)),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Plugin options, as JSON.')),
                ('merge_variables', models.JSONField(blank=True, default=dict, help_text='Data the templates render. Filled by the webhook, by polling, or by hand.')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('refresh_interval', models.PositiveIntegerField(default=15, help_text='Minutes between data refreshes and re-renders.')),
                ('data_refreshed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_error', models.TextField(blank=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='django_trmnl_byos.device')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='django_trmnl_byos.playlist'),
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('refresh_rate', models.PositiveIntegerField(blank=True, help_text="Seconds to show this item. Blank uses the device's rate.", null=True)),
                ('start_time', models.TimeField(blank=True, help_text='Only show from this local time.', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Only show until this local time.', null=True)),
                ('weekdays', models.CharField(blank=True, default='0123456', help_text='Days to show, as digits: 0 = Monday … 6 = Sunday.', max_length=7)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_items', to='django_trmnl_byos.dashboard')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='django_trmnl_byos.playlist')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='DashboardCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=1, help_text='Slot number in a fixed layout, in markup order.')),
                ('col', models.PositiveSmallIntegerField(default=1, help_text='Fluid only: starting column (1-3).')),
                ('row', models.PositiveSmallIntegerField(default=1, help_text='Fluid only: starting row (1-3).')),
                ('col_span', models.PositiveSmallIntegerField(default=1, help_text='Fluid only: columns spanned.')),
                ('row_span', models.PositiveSmallIntegerField(default=1, help_text='Fluid only: rows spanned.')),
                ('show_title_bar', models.BooleanField(default=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='django_trmnl_byos.dashboard')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='django_trmnl_byos.plugininstance')),
            ],
            options={
                'ordering': ['position', 'row', 'col'],
            },
        ),
        migrations.CreateModel(
            name='Render',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile', models.CharField(choices=[('og', 'TRMNL OG (1-bit)'), ('og_2bit', 'TRMNL OG (2-bit, firmware 1.6+)'), ('x', 'TRMNL X (4-bit)')], max_length=20)),
                ('orientation', models.CharField(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait')], default='landscape', max_length=10)),
                ('image', models.BinaryField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('html', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renders', to='django_trmnl_byos.dashboard')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='last_render',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='django_trmnl_byos.render'),
        ),
    ]
