# Generated by Django 6.0.8 on 2026-09-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_trmnl_byos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='profile',
            field=models.CharField(choices=[('og', 'TRMNL OG (1-bit)'), ('og_2bit', 'TRMNL OG (2-bit, firmware 1.6+)'), ('x', 'TRMNL X (4-bit)'), ('small_400x300', 'Small 400×300 (1-bit, e.g. Zectrix Note 4)')], default='og', max_length=20),
        ),
        migrations.AlterField(
            model_name='render',
            name='profile',
            field=models.CharField(choices=[('og', 'TRMNL OG (1-bit)'), ('og_2bit', 'TRMNL OG (2-bit, firmware 1.6+)'), ('x', 'TRMNL X (4-bit)'), ('small_400x300', 'Small 400×300 (1-bit, e.g. Zectrix Note 4)')], max_length=20),
        ),
    ]
