# Generated by Django 6.0.8 on 2026-10-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_trmnl_byos', '0002_profile_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='profile',
            field=models.CharField(choices=[('og', 'TRMNL OG (1-bit)'), ('og_2bit', 'TRMNL OG (2-bit, firmware 1.6+)'), ('x', 'TRMNL X (4-bit)'), ('small_400x300', 'Small 400×300 (1-bit, e.g. Zectrix Note 4)'), ('color_400x300', 'Colour 400×300 (black/white/yellow/red, e.g. Zectrix Note 4C)')], default='og', max_length=20),
        ),
        migrations.AlterField(
            model_name='render',
            name='profile',
            field=models.CharField(choices=[('og', 'TRMNL OG (1-bit)'), ('og_2bit', 'TRMNL OG (2-bit, firmware 1.6+)'), ('x', 'TRMNL X (4-bit)'), ('small_400x300', 'Small 400×300 (1-bit, e.g. Zectrix Note 4)'), ('color_400x300', 'Colour 400×300 (black/white/yellow/red, e.g. Zectrix Note 4C)')], max_length=20),
        ),
    ]
